name: "MANUAL Terraform Destroy automated workflow"

on: workflow_dispatch

env: 
  TF_LOG: INFO
  TF_STATE_BUCKET_PROD: ${{ vars.TF_STATE_BUCKET_PROD }}
  TF_STATE_KEY_PROD: ${{ vars.TF_STATE_KEY_PROD }}
  TF_STATE_DDBTABLE_PROD: ${{ vars.TF_STATE_DDBTABLE_PROD }}

  TF_STATE_BUCKET_DEV: ${{ vars.TF_STATE_BUCKET_DEV }}
  TF_STATE_KEY_DEV: ${{ vars.TF_STATE_KEY_DEV }}
  TF_STATE_DDBTABLE_DEV: ${{ vars.TF_STATE_DDBTABLE_DEV }}

  TF_STATE_REGION: ${{ vars.TF_STATE_REGION }}
  AWS_REGION: us-east-1 # This only dictates the default region for API and CLI commands, but region is always specified on a per command basis, so it doesn't matter
  AWS_ROLE_DEV: ${{vars.AWS_ROLE_DEV}}
  AWS_ROLE_PROD: ${{vars.AWS_ROLE_PROD}}

  AWS_HOSTEDZONE_PROD: ${{vars.AWS_HOSTEDZONE_PROD}}
  AWS_HOSTEDZONE_DEV: ${{vars.AWS_HOSTEDZONE_DEV}}
  AWS_SITENAME: ${{ vars.AWS_SITENAME }}
  
# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: "TF Infrastrcture Destroy BE and FE"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
        working-directory: ./tf-main
        

    steps:
      - name: Checkout the repository to the runner
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        uses: actions/checkout@v3

      - name: configure aws credentials DEV
        if: github.ref_name == 'Test'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_DEV }} 
          aws-region: ${{ env.AWS_REGION }}

      - name: configure aws credentials PROD
        if: github.ref_name == 'main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ env.AWS_ROLE_PROD }} #change to reflect your IAM role’s ARN
            aws-region: ${{ env.AWS_REGION }}
          
      - name: Setup Terraform with specified version on the runner
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Terraform Init PROD
        id: initPROD
        if: github.ref_name == 'main'
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_PROD" -backend-config="key=$TF_STATE_KEY_PROD" -backend-config="region=$TF_STATE_REGION" -backend-config="dynamodb_table=$TF_STATE_DDBTABLE_PROD"

      - name: Terraform Init DEV
        id: initDEV
        if: github.ref_name == 'Test'
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_DEV" -backend-config="key=$TF_STATE_KEY_DEV" -backend-config="region=$TF_STATE_REGION" -backend-config="dynamodb_table=$TF_STATE_DDBTABLE_DEV"

      - name: Terraform Validate
        id: validate
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        run: terraform validate

      - name: Terraform State List
        id: statelist
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        run: terraform state list

      - name: Terraform Destory - with Retry - Dev
        id: destroy-retry-dev
        if: github.ref_name == 'Test'
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          retry_on: any
          timeout_minutes: 30
          retry_wait_seconds: 30
          shell: bash
          command: terraform destroy -auto-approve -input=false -var-file="terraform.tfvars" -var "HostedZone=$AWS_HOSTEDZONE_DEV" -var "WebSiteHostName=$AWS_SITENAME"


      - name: Terraform Destory - with Retry - Dev
        id: destroy-retry-prod
        if: github.ref_name == 'main'
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          retry_on: any
          timeout_minutes: 30
          retry_wait_seconds: 30
          shell: bash
          command: terraform destroy -auto-approve -input=false -var-file="terraform.tfvars" -var "HostedZone=$AWS_HOSTEDZONE_PROD" -var "WebSiteHostName=$AWS_SITENAME"

      