name: "MANUAL Terraform Destroy automated workflow"

on: workflow_dispatch

env: 
  TF_LOG: INFO
  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
  TF_STATE_KEY_MAIN: ${{ vars.TF_STATE_KEY_MAIN }}
  TF_STATE_DDBTABLE: ${{ vars.TF_STATE_DDBTABLE }}
  TF_STATE_REGION: ${{ vars.TF_STATE_REGION }}
  AWS_REGION: us-east-1 # This only dictates the default region for API and CLI commands, but region is always specified on a per command basis, so it doesn't matter
  AWS_ROLE_DEV: ${{vars.AWS_ROLE_DEV}}
  AWS_ROLE_PROD: ${{vars.AWS_ROLE_PROD}}
  
# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: "TF Infrastrcture Destroy BE and FE"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
        working-directory: ./tf-main
        

    steps:
      - name: Checkout the repository to the runner
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        uses: actions/checkout@v3

      - name: configure aws credentials
        if: github.ref_name == 'Test'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_DEV }} 
          aws-region: ${{ env.AWS_REGION }}

      - name: configure aws credentials
        if: github.ref_name == 'main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ env.AWS_ROLE_PROD }} #change to reflect your IAM role’s ARN
            aws-region: ${{ env.AWS_REGION }}
          
      - name: Setup Terraform with specified version on the runner
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Terraform Init Main
        id: init
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=$TF_STATE_KEY_MAIN" -backend-config="region=$TF_STATE_REGION" -backend-config="dynamodb_table=$TF_STATE_DDBTABLE"
      
      - name: Terraform Validate Main
        id: validate
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        run: terraform validate

      - name: Terraform Destory Main - with Retry
        id: destroy-retry
        if: github.ref_name == 'Test' || github.ref_name == 'main'
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          retry_on: any
          timeout_minutes: 30
          retry_wait_seconds: 30
          shell: bash
          command: terraform destroy -auto-approve
      